-- Watchdog greenfield Postgres init
-- Better Auth → auth schema; product tables → public

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS auth;

DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'watchdog_app') THEN
        CREATE ROLE watchdog_app WITH LOGIN PASSWORD 'watchdog';
    END IF;
END $$;

GRANT CONNECT ON DATABASE watchdog TO watchdog_app;
GRANT CREATE ON DATABASE watchdog TO watchdog_app;
GRANT USAGE, CREATE ON SCHEMA public, auth TO watchdog_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO watchdog_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO watchdog_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO watchdog_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT USAGE ON SEQUENCES TO watchdog_app;
