/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiV1RouteImport } from './routes/api/v1'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as ProtectedCasesIndexRouteImport } from './routes/_protected/cases/index'
import { Route as ProtectedCasesCaseSlugRouteImport } from './routes/_protected/cases/$caseSlug'
import { Route as ProtectedEntitiesIndexRouteImport } from './routes/_protected/entities/index'
import { Route as ProtectedEntitiesEntitySlugRouteImport } from './routes/_protected/entities/$entitySlug'
import { Route as ProtectedGraphIndexRouteImport } from './routes/_protected/graph/index'
import { Route as ProtectedIdentifiersIndexRouteImport } from './routes/_protected/identifiers/index'
import { Route as ProtectedInboxIndexRouteImport } from './routes/_protected/inbox/index'
import { Route as ProtectedIntakeIndexRouteImport } from './routes/_protected/intake/index'
import { Route as ProtectedJobsIndexRouteImport } from './routes/_protected/jobs/index'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedTasksIndexRouteImport } from './routes/_protected/tasks/index'
import { Route as ProtectedUiIndexRouteImport } from './routes/_protected/ui/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1.$'
import { Route as ApiV1CasesCaseIdExportDotzipRouteImport } from './routes/api/v1/cases.$caseId.export[.]zip'
import { Route as ApiV1CasesCaseIdEntitiesSlugExportDotmdRouteImport } from './routes/api/v1/cases.$caseId.entities.$slug.export[.]md'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1Route = ApiV1RouteImport.update({
  id: '/api/v1',
  path: '/api/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedCasesIndexRoute = ProtectedCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCasesCaseSlugRoute = ProtectedCasesCaseSlugRouteImport.update({
  id: '/cases/$caseSlug',
  path: '/cases/$caseSlug',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedEntitiesIndexRoute = ProtectedEntitiesIndexRouteImport.update({
  id: '/entities/',
  path: '/entities/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedEntitiesEntitySlugRoute =
  ProtectedEntitiesEntitySlugRouteImport.update({
    id: '/entities/$entitySlug',
    path: '/entities/$entitySlug',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedGraphIndexRoute = ProtectedGraphIndexRouteImport.update({
  id: '/graph/',
  path: '/graph/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedIdentifiersIndexRoute =
  ProtectedIdentifiersIndexRouteImport.update({
    id: '/identifiers/',
    path: '/identifiers/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedInboxIndexRoute = ProtectedInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedIntakeIndexRoute = ProtectedIntakeIndexRouteImport.update({
  id: '/intake/',
  path: '/intake/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedJobsIndexRoute = ProtectedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTasksIndexRoute = ProtectedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUiIndexRoute = ProtectedUiIndexRouteImport.update({
  id: '/ui/',
  path: '/ui/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiV1Route,
} as any)
const ApiV1CasesCaseIdExportDotzipRoute =
  ApiV1CasesCaseIdExportDotzipRouteImport.update({
    id: '/cases/$caseId/export.zip',
    path: '/cases/$caseId/export.zip',
    getParentRoute: () => ApiV1Route,
  } as any)
const ApiV1CasesCaseIdEntitiesSlugExportDotmdRoute =
  ApiV1CasesCaseIdEntitiesSlugExportDotmdRouteImport.update({
    id: '/cases/$caseId/entities/$slug/export.md',
    path: '/cases/$caseId/entities/$slug/export.md',
    getParentRoute: () => ApiV1Route,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/api/events': typeof ApiEventsRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/auth/$path': typeof AuthPathRoute
  '/cases/$caseSlug': typeof ProtectedCasesCaseSlugRoute
  '/entities/$entitySlug': typeof ProtectedEntitiesEntitySlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/cases/': typeof ProtectedCasesIndexRoute
  '/entities/': typeof ProtectedEntitiesIndexRoute
  '/graph/': typeof ProtectedGraphIndexRoute
  '/identifiers/': typeof ProtectedIdentifiersIndexRoute
  '/inbox/': typeof ProtectedInboxIndexRoute
  '/intake/': typeof ProtectedIntakeIndexRoute
  '/jobs/': typeof ProtectedJobsIndexRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/tasks/': typeof ProtectedTasksIndexRoute
  '/ui/': typeof ProtectedUiIndexRoute
  '/api/v1/cases/$caseId/export.zip': typeof ApiV1CasesCaseIdExportDotzipRoute
  '/api/v1/cases/$caseId/entities/$slug/export.md': typeof ApiV1CasesCaseIdEntitiesSlugExportDotmdRoute
}
export interface FileRoutesByTo {
  '/api/events': typeof ApiEventsRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/auth/$path': typeof AuthPathRoute
  '/': typeof ProtectedIndexRoute
  '/cases/$caseSlug': typeof ProtectedCasesCaseSlugRoute
  '/entities/$entitySlug': typeof ProtectedEntitiesEntitySlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/cases': typeof ProtectedCasesIndexRoute
  '/entities': typeof ProtectedEntitiesIndexRoute
  '/graph': typeof ProtectedGraphIndexRoute
  '/identifiers': typeof ProtectedIdentifiersIndexRoute
  '/inbox': typeof ProtectedInboxIndexRoute
  '/intake': typeof ProtectedIntakeIndexRoute
  '/jobs': typeof ProtectedJobsIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/tasks': typeof ProtectedTasksIndexRoute
  '/ui': typeof ProtectedUiIndexRoute
  '/api/v1/cases/$caseId/export.zip': typeof ApiV1CasesCaseIdExportDotzipRoute
  '/api/v1/cases/$caseId/entities/$slug/export.md': typeof ApiV1CasesCaseIdEntitiesSlugExportDotmdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/api/events': typeof ApiEventsRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/auth/$path': typeof AuthPathRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/cases/$caseSlug': typeof ProtectedCasesCaseSlugRoute
  '/_protected/entities/$entitySlug': typeof ProtectedEntitiesEntitySlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/_protected/cases/': typeof ProtectedCasesIndexRoute
  '/_protected/entities/': typeof ProtectedEntitiesIndexRoute
  '/_protected/graph/': typeof ProtectedGraphIndexRoute
  '/_protected/identifiers/': typeof ProtectedIdentifiersIndexRoute
  '/_protected/inbox/': typeof ProtectedInboxIndexRoute
  '/_protected/intake/': typeof ProtectedIntakeIndexRoute
  '/_protected/jobs/': typeof ProtectedJobsIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/tasks/': typeof ProtectedTasksIndexRoute
  '/_protected/ui/': typeof ProtectedUiIndexRoute
  '/api/v1/cases/$caseId/export.zip': typeof ApiV1CasesCaseIdExportDotzipRoute
  '/api/v1/cases/$caseId/entities/$slug/export.md': typeof ApiV1CasesCaseIdEntitiesSlugExportDotmdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/events'
    | '/api/v1'
    | '/auth/$path'
    | '/cases/$caseSlug'
    | '/entities/$entitySlug'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/v1/$'
    | '/cases/'
    | '/entities/'
    | '/graph/'
    | '/identifiers/'
    | '/inbox/'
    | '/intake/'
    | '/jobs/'
    | '/settings/'
    | '/tasks/'
    | '/ui/'
    | '/api/v1/cases/$caseId/export.zip'
    | '/api/v1/cases/$caseId/entities/$slug/export.md'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/events'
    | '/api/v1'
    | '/auth/$path'
    | '/'
    | '/cases/$caseSlug'
    | '/entities/$entitySlug'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/v1/$'
    | '/cases'
    | '/entities'
    | '/graph'
    | '/identifiers'
    | '/inbox'
    | '/intake'
    | '/jobs'
    | '/settings'
    | '/tasks'
    | '/ui'
    | '/api/v1/cases/$caseId/export.zip'
    | '/api/v1/cases/$caseId/entities/$slug/export.md'
  id:
    | '__root__'
    | '/_protected'
    | '/api/events'
    | '/api/v1'
    | '/auth/$path'
    | '/_protected/'
    | '/_protected/cases/$caseSlug'
    | '/_protected/entities/$entitySlug'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/v1/$'
    | '/_protected/cases/'
    | '/_protected/entities/'
    | '/_protected/graph/'
    | '/_protected/identifiers/'
    | '/_protected/inbox/'
    | '/_protected/intake/'
    | '/_protected/jobs/'
    | '/_protected/settings/'
    | '/_protected/tasks/'
    | '/_protected/ui/'
    | '/api/v1/cases/$caseId/export.zip'
    | '/api/v1/cases/$caseId/entities/$slug/export.md'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ApiEventsRoute: typeof ApiEventsRoute
  ApiV1Route: typeof ApiV1RouteWithChildren
  AuthPathRoute: typeof AuthPathRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1': {
      id: '/api/v1'
      path: '/api/v1'
      fullPath: '/api/v1'
      preLoaderRoute: typeof ApiV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/cases/': {
      id: '/_protected/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof ProtectedCasesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/cases/$caseSlug': {
      id: '/_protected/cases/$caseSlug'
      path: '/cases/$caseSlug'
      fullPath: '/cases/$caseSlug'
      preLoaderRoute: typeof ProtectedCasesCaseSlugRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/entities/': {
      id: '/_protected/entities/'
      path: '/entities'
      fullPath: '/entities/'
      preLoaderRoute: typeof ProtectedEntitiesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/entities/$entitySlug': {
      id: '/_protected/entities/$entitySlug'
      path: '/entities/$entitySlug'
      fullPath: '/entities/$entitySlug'
      preLoaderRoute: typeof ProtectedEntitiesEntitySlugRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/graph/': {
      id: '/_protected/graph/'
      path: '/graph'
      fullPath: '/graph/'
      preLoaderRoute: typeof ProtectedGraphIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/identifiers/': {
      id: '/_protected/identifiers/'
      path: '/identifiers'
      fullPath: '/identifiers/'
      preLoaderRoute: typeof ProtectedIdentifiersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/inbox/': {
      id: '/_protected/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof ProtectedInboxIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/intake/': {
      id: '/_protected/intake/'
      path: '/intake'
      fullPath: '/intake/'
      preLoaderRoute: typeof ProtectedIntakeIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/jobs/': {
      id: '/_protected/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof ProtectedJobsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tasks/': {
      id: '/_protected/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof ProtectedTasksIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/ui/': {
      id: '/_protected/ui/'
      path: '/ui'
      fullPath: '/ui/'
      preLoaderRoute: typeof ProtectedUiIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof ApiV1Route
    }
    '/api/v1/cases/$caseId/export.zip': {
      id: '/api/v1/cases/$caseId/export.zip'
      path: '/cases/$caseId/export.zip'
      fullPath: '/api/v1/cases/$caseId/export.zip'
      preLoaderRoute: typeof ApiV1CasesCaseIdExportDotzipRouteImport
      parentRoute: typeof ApiV1Route
    }
    '/api/v1/cases/$caseId/entities/$slug/export.md': {
      id: '/api/v1/cases/$caseId/entities/$slug/export.md'
      path: '/cases/$caseId/entities/$slug/export.md'
      fullPath: '/api/v1/cases/$caseId/entities/$slug/export.md'
      preLoaderRoute: typeof ApiV1CasesCaseIdEntitiesSlugExportDotmdRouteImport
      parentRoute: typeof ApiV1Route
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedCasesCaseSlugRoute: typeof ProtectedCasesCaseSlugRoute
  ProtectedEntitiesEntitySlugRoute: typeof ProtectedEntitiesEntitySlugRoute
  ProtectedCasesIndexRoute: typeof ProtectedCasesIndexRoute
  ProtectedEntitiesIndexRoute: typeof ProtectedEntitiesIndexRoute
  ProtectedGraphIndexRoute: typeof ProtectedGraphIndexRoute
  ProtectedIdentifiersIndexRoute: typeof ProtectedIdentifiersIndexRoute
  ProtectedInboxIndexRoute: typeof ProtectedInboxIndexRoute
  ProtectedIntakeIndexRoute: typeof ProtectedIntakeIndexRoute
  ProtectedJobsIndexRoute: typeof ProtectedJobsIndexRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
  ProtectedTasksIndexRoute: typeof ProtectedTasksIndexRoute
  ProtectedUiIndexRoute: typeof ProtectedUiIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedCasesCaseSlugRoute: ProtectedCasesCaseSlugRoute,
  ProtectedEntitiesEntitySlugRoute: ProtectedEntitiesEntitySlugRoute,
  ProtectedCasesIndexRoute: ProtectedCasesIndexRoute,
  ProtectedEntitiesIndexRoute: ProtectedEntitiesIndexRoute,
  ProtectedGraphIndexRoute: ProtectedGraphIndexRoute,
  ProtectedIdentifiersIndexRoute: ProtectedIdentifiersIndexRoute,
  ProtectedInboxIndexRoute: ProtectedInboxIndexRoute,
  ProtectedIntakeIndexRoute: ProtectedIntakeIndexRoute,
  ProtectedJobsIndexRoute: ProtectedJobsIndexRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
  ProtectedTasksIndexRoute: ProtectedTasksIndexRoute,
  ProtectedUiIndexRoute: ProtectedUiIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface ApiV1RouteChildren {
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiV1CasesCaseIdExportDotzipRoute: typeof ApiV1CasesCaseIdExportDotzipRoute
  ApiV1CasesCaseIdEntitiesSlugExportDotmdRoute: typeof ApiV1CasesCaseIdEntitiesSlugExportDotmdRoute
}

const ApiV1RouteChildren: ApiV1RouteChildren = {
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiV1CasesCaseIdExportDotzipRoute: ApiV1CasesCaseIdExportDotzipRoute,
  ApiV1CasesCaseIdEntitiesSlugExportDotmdRoute:
    ApiV1CasesCaseIdEntitiesSlugExportDotmdRoute,
}

const ApiV1RouteWithChildren = ApiV1Route._addFileChildren(ApiV1RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  ApiEventsRoute: ApiEventsRoute,
  ApiV1Route: ApiV1RouteWithChildren,
  AuthPathRoute: AuthPathRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
